inIncome= enlightenMe("income")
rent= enlightenMe("rent")
utilities= enlightenMe("utilites")
Groceries= enlightenMe("groceries")
transportation= enlightenMe("transportation")
percentageSavings = enlightenMe("percentagesavings")